// random user data

const fakeData = {
  users: [
    {
      name: "Admin",
      email: "admin@example.com",
      password: "Admin$1234",
      address: "Dhaka",
      phone: "01712345678",
      isAdmin: true,
    },
    {
      name: "Banned",
      email: "banned@example.com",
      password: "Banned$1234",
      address: "New York",
      phone: "1234567890",
      isBanned: true,
    },
    {
      name: "Mary Johnson",
      email: "mary.johnson@example.com",
      password: "MJohnson$abcd",
      address: "Los Angeles",
      phone: "9876543210",
    },
    {
      name: "David Wilson",
      email: "david.wilson@example.com",
      password: "DWilson$qwerty",
      address: "London",
      phone: "5555555555",
    },
    {
      name: "Emily Davis",
      email: "emily.davis@example.com",
      password: "EDavis$p@ssw0rd",
      address: "Paris",
      phone: "5551234567",
    },
    {
      name: "Michael Brown",
      email: "michael.brown@example.com",
      password: "MBrown$12345",
      address: "Berlin",
      phone: "1234567890",
    },
    {
      name: "Sarah Smith",
      email: "sarah.smith@example.com",
      password: "SSmith$abcde",
      address: "Sydney",
      phone: "9876543210",
    },
    {
      name: "Daniel Johnson",
      email: "daniel.johnson@example.com",
      password: "DJohnson$pass123",
      address: "Toronto",
      phone: "5555555555",
    },
    {
      name: "Olivia Wilson",
      email: "olivia.wilson@example.com",
      password: "OWilson$secret",
      address: "Tokyo",
      phone: "5551234567",
    },
    {
      name: "William Davis",
      email: "william.davis@example.com",
      password: "WDavis$password",
      address: "Beijing",
      phone: "1234567890",
    },
    {
      name: "Sophia Brown",
      email: "sophia.brown@example.com",
      password: "SBrown$5678",
      address: "Moscow",
      phone: "9876543210",
    },
    {
      name: "James Smith",
      email: "james.smith@example.com",
      password: "JSmith$abcd",
      address: "Rio de Janeiro",
      phone: "5555555555",
    },
    {
      name: "Emma Johnson",
      email: "emma.johnson@example.com",
      password: "EJohnson$qwerty",
      address: "Cape Town",
      phone: "5551234567",
    },
    {
      name: "Benjamin Wilson",
      email: "benjamin.wilson@example.com",
      password: "BWilson$p@ssw0rd",
      address: "Hong Kong",
      phone: "1234567890",
    },
    {
      name: "Mia Davis",
      email: "mia.davis@example.com",
      password: "MDavis$12345",
      address: "Singapore",
      phone: "9876543210",
    },
    {
      name: "Liam Brown",
      email: "liam.brown@example.com",
      password: "LBrown$abcde",
      address: "Dubai",
      phone: "5555555555",
    },
    {
      name: "Ava Smith",
      email: "ava.smith@example.com",
      password: "ASmith$pass123",
      address: "Istanbul",
      phone: "5551234567",
    },
    {
      name: "Logan Johnson",
      email: "logan.johnson@example.com",
      password: "LJohnson$secret",
      address: "Mumbai",
      phone: "1234567890",
    },
    {
      name: "Ella Wilson",
      email: "ella.wilson@example.com",
      password: "EWilson$password",
      address: "Seoul",
      phone: "9876543210",
    },
    {
      name: "Noah Davis",
      email: "noah.davis@example.com",
      password: "NDavis$5678",
      address: "Mexico City",
      phone: "5555555555",
    },
  ],
};

module.exports = fakeData;
